# Generated by Django 2.1.4 on 2019-04-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_ConfirmString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '确认码',
                'verbose_name_plural': '确认码',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='has_eamil_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email_confirmstring',
            name='user',
            field=models.OneToOneField(on_delete='on_delete', to='register.User'),
        ),
    ]
